### ISSUE TITLE
getting errors when running in ubuntu in AWS EC2

### ISSUE THREAD

**Issue by buryhuang** [mzxrai/mcp-webresearch#9]
I'm running this with https://github.com/SecretiveShell/MCP-Bridge
It returns the search results sometimes back to the chat, but it errors out on the console.
I have updated the machine to have node 22 (it gave same error when it was on node 18)

```
node --version
v22.12.0
```

It's working very well on my Mac.

```
Received ListToolsRequest
Attempt 1 failed, retrying in 1000ms: page.evaluate: Error: No search results found
    at eval (eval at evaluate (:234:30), <anonymous>:5:39)
    at UtilityScript.evaluate (<anonymous>:236:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at /home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:706:52
    at withRetry (/home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:148:26)
    at /home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:705:49
    at async withRetry (/home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:148:20)
    at /home/ubuntu/MCP-Bridge/async file:/home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:669:33
Attempt 1 failed, retrying in 1000ms: page.evaluate: Error: No search results found
    at eval (eval at evaluate (:234:30), <anonymous>:5:39)
    at UtilityScript.evaluate (<anonymous>:236:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at /home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:706:52
    at withRetry (/home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:148:26)
    at /home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:705:49
    at async withRetry (/home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:148:20)
    at /home/ubuntu/MCP-Bridge/async file:/home/ubuntu/.npm/_npx/bd29c0cb7c2b284c/node_modules/@mzxrai/mcp-webresearch/dist/index.js:669:33
INFO:     100.26.180.96:42794 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     54.82.117.31:41704 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by buryhuang** [comment]
It seems getting more error lately with running locally. Do you know if there may be any thing changed on google or the code?

```
{
  `query`: `Daily.co company funding stage video API`
}
Failed to perform search: page.evaluate: Execution context was destroyed, most likely because of a navigation
```
